### ISSUE TITLE
Unable to trigger IRBlaster via HomeKit - only working via direct URL request

### ISSUE THREAD

**Issue by scoover** [NorthernMan54/homebridge-HTTP-IRBlaster#1]
Picking up on [this issue](https://github.com/nfarina/homebridge/issues/2125) originally posted in [homebridge](https://github.com/nfarina/homebridge) regarding homebridge connectivity to an HTTP-IRBlaster triggered by HomeKit...

There seems to be an issue with my homebridge setup:
1. I can trigger the IRBlaster with a direct URL request. 
2. My homebridge config.json is causing my device to properly display in iOS HomeKit. 
3. But, I am not able to trigger the IRBlaster device from HomeKit. 

NorthernMan54 said:

> I took a quick look, and it appears the sample-config.json is outdated and doesn’t reflect the current code base. If you look at the README, it is current.
> 
> Majour difference is I switched from the URL config option to irblaster.  Which is the devices hostname.  Hence the dns error and enotfound error
> 

Are you saying that I delete the "url" keyword and set "irBlaster" to the hostname that I assigned the the blaster wifi setup process? e.g.:
`"irBlaster": "fireplace",`

...and then the passcode I setup would go right below that like this?
`"irBlaster": "fireplace",`
`"pass":"100",`

Where does the port number go? Is it part of the irBlaster definition? e.g.
`"irBlaster": "fireplace.local:667"`
or?
`"irBlaster": "192.168.1.16:667"`

What about the minimal output keyword you had used in previous examples "simple=1"? Necessary?
Any other changes required to config.json?

Three other questions:
* You suggested a 23cm wire for the antenna.... I can just hang a long wire off the end of the TX pcb?
* Do you know if the remotes are paired to the fireplace inserts? Or if your codes should work on all inserts with the same remote FCC ID?
* As for Github hygiene... would you still like me to repost this to your GitHub project? Should I close it on the other ones (even with no responses)?

Sorry for so many questions; really appreciate your help! 
It's a super cool project and I can't wait to get it working.
Randy

P.S. I'm running Homebridge version 0.4.45 and node version v11.7.0 on a 2013 Mac Pro (Mojave 10.14.2).

**Comment by NorthernMan54** [comment]
First question the url/passcode

If you look at the code, I build up the url for the http request here

https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster/blob/5ee77125c1d685240fdb671a3cbd3cda8d9390e7/index.js#L79

Where I combine irblaster ( hostname ) with the command config option.  If you look earlier in the code I default the command config option to /json?simple=1.  So if you need to add options to the command string, you do need to include /json?simple=1 as part of it.

If you have changed the default http port of the device and set a passcode then you would need to set a command option with all those pieces so that the device url is properly constructed.  I hope that with this insight and a bit of trial and error, you can come up with the correct command option based on your config.

2 antenna - my device sits about 10 feet from the fireplace and the antenna is just curled into a loop inside the enclosure I’m using for the esp8266.   For me it works fine.  In the same enclosure I have a second transmitter for my Hampton bay fans, with its antenna also curled in the enclosure and the fans are on the far side of the house and they work fine as well.

3 codes and pairing - I have only seen one of these devices, so I don’t know how pairing or codes work for these devices, but I would expect something.  If you can capture the signals from your remote and compare with my samples you should be able to identify the code versus command portion of the signal.

But for the config, you just need the on/off timing for the transmitter to generate the same signal that your remote generates.  Once I had everything setup, it took me about 8 hours of trial and error to have the device replicate the remote signal. 

4 github hygiene - the polite thing to do is close the issues in the other locations, as it saves the repo owner same time.  And if you left a breadcrumb in it saying where you went with the issue, even better for anyone who stumbles across it in the future.

For me, the fireplace control has the highest WAF score of all my home automation projects, as they couldn’t get the factory remote to work consistently.  And once I add Alexa to the mix, it went off the scale.  Alexa turn on fireplace, Alexa turn fireplace to 30, Alexa turn off fireplace

Also, in my setup I have a temperature sensor in the same room as the fireplace, and I have an automation setup to turn off the fireplace if it gets too warm.  And a second one that turns it off everyday at a particular time, Incase it gets turned on by mistake.

**Comment by scoover** [comment]
Thanks for the quick feedback, NorthernMan54. Here are a few updates:
1. I changed the IRBlaster reference to `"irBlaster": "fireplace.local"` in the homebridge config.json.
2. I stripped the `url` keyword out of the homebridge config.json.
3. I removed the passcode from my HTTP-IRBlaster configuration.
4. I stripped the `pass` keyword out of the homebridge config.json.

And (... drumroll...) now I can successfully send requests to the HTTP-IRBlaster via iOS Homekit.

I think you are saying that a HTTP-IRBlaster passcode is not currently supported in your homebridge-HTTP-IRBlaster project, right? I didn't see any references to it in the [index.js](https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster/blob/5ee77125c1d685240fdb671a3cbd3cda8d9390e7/index.js#L79).

Now my only outstanding issue is getting the fireplace to receive the commands— it's either an antenna issue, the [TX component I'm using](https://www.amazon.com/gp/product/B007R9UITK/ref=ppx_yo_dt_b_asin_title_o03__o00_s00), or a tweak to the RF codes. Will investigate...

Thanks for posting and supporting this project!
Randy

P.S. I closed my github issues in homebridge and HTTP-IRBlaster.

**Comment by NorthernMan54** [comment]
Do you have a RTL-SDR so you can look at the signals your remote is sending versus the device?

**Comment by scoover** [comment]
I don't have that yet. I will try a better antenna tomorrow (with your TX codes). If that doesn't work, I've got a RX module that I'll hook up to an oscilloscope. And if that doesn't work, then I'll buy a RTL-SDR.

Again, your project doesn't support HTTP-IRBlaster passcodes?

Thanks for the encouragement!
Randy

**Comment by NorthernMan54** [comment]
Last year I decoded a couple of different RF Remotes, starting with this one.  And to decode them, I found that using an RTL-SDR was the fastest.  My workflow was

Capture remote with RTL-SDR
Visualize captured signal with Audacity, and screen cap a single burst
Pull screen cap into Google Sheets and determine pulses

**Comment by scoover** [comment]
My fireplace still isn't hearing the IR-Blaster— even with the bigger antenna. The next step is to get a better picture of what is being transmitted by the fireplace remote and also by my IR-Blaster. 

So, I've ordered the RTL-SDR as you recommended. Should have more info later this week. Thanks.

**Comment by NorthernMan54** [comment]
Tks for closing this

**Comment by scoover** [comment]
I’m sorry it took so long. I lost track of it.
Thanks for your patience.
